#!/usr/bin/env bash
set -e

which atom || (
    cd /tmp
    wget https://atom-installer.github.com/v1.4.3/atom-amd64.deb
    sudo dpkg -i atom-amd64.deb
)

cd /tmp
wget https://github.com/i-tu/Hasklig/releases/download/0.9/Hasklig-0.9.zip
unzip Hasklig-0.9.zip
mv Hasklig-*.otf ~/.fonts

apm install \
    Sublime-Style-Column-Selection@1.5.1 \
    autocomplete-haskell@0.6.2 \
    box-edit@0.1.3 \
    file-icons@1.6.14 \
    haskell-ghc-mod@1.6.4 \
    highlight-selected@0.11.2 \
    ide-haskell@1.3.9 \
    ide-haskell-cabal@1.0.0 \
    ide-haskell-hasktags@0.0.1 \
    keybinding-cheatsheet@0.1.0 \
    language-haskell@1.5.2 \
    minimap@4.19.0 \
    minimap-codeglance@0.4.5 \
    minimap-highlight-selected@4.3.1 \
    pigments@0.23.1 \
    simple-align@0.1.0 \
    sort-lines@0.14.0 \
    swap-selection@0.3.0 \
    todo-show@1.3.0 \
    vim-mode@0.64.0 \
    wordcount@2.6.0

#   color-picker@2.1.1 \
#   hex@0.6.2 \
#   language-rust@0.4.5 \
#   merge-conflicts@1.3.7 \
